apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.87.252:3260
     iqn: iqn.testTGT.ths-storage.ths.tue.nl:lun1
     lun: 1
     fsType: 'ext4'
     readOnly: false